### ISSUE TITLE
Improve Slider UX

### ISSUE THREAD

**Issue by kancijan** [infinum/eightshift-ui-components#1]
![image](https://github.com/infinum/eightshift-ui-components/assets/135589039/270db751-9dc0-4822-8311-8c11c30a8600)

Grid handles don't have any visual feedback when they are dragged.

I suggest you add cursor grab and grabbing on click.
![image](https://github.com/infinum/eightshift-ui-components/assets/135589039/8e074505-ba5e-4207-a649-b3ecc9a43023)

**Comment by goranalkovic-infinum** [comment]
Fixed in 1.2.1
