### ISSUE TITLE
Consider changing behaviour of LinkInput component re swithching focus to suggestios panel

### ISSUE THREAD

**Issue by piqusy** [infinum/eightshift-ui-components#2]
Trying to add a custom URL seems cumbersome since the focus switches to suggestions panel after a while and cannot go back without using the mouse.

I'd suggest implementing a key to switch focus instead of switching focus automatically.
It would make sense to map that functionality to `tab` key.

Screen recording:
https://github.com/user-attachments/assets/c3ba89cd-cc2d-4fd5-bb63-434fb5a0e80f

**Comment by goranalkovic-infinum** [comment]
In UI components 1.4.x this is now ignored for `www.`

Also, if suggestions are shown, the input field is still focused, you need to press down arrow to focus on it.
